---
layout: post
title:  "0423-[자바]-exception"
subtitle:   "0423-exception"
categories: devlog
tags: Java

---
## excetion

<hr style="height: 1px; background: skyblue; "/>

#### TryCatch

~~~


package g_exception;

/*
	오류
		-에러: 심각한 오류
		-예외: 심각하지 않은 오류

	(1) 예외를 잡자 - try ~ catch 구문
		try {
			예외 발생할 구문
		}catch(){
			예외가 발생한 후의 구문
		}finally{
			예외 발생 여부 상관없이 무조건 실행 구문
		}
*/

public class Ex01_TryCatch {

	public static void main(String[] args) {

		String[] str = { "맛점", "우산", "즐거운화요일" };

		try {

			for (int i = 0; i < str.length; i++) {
				System.out.println(str[i]);
			}
			System.out.println("예외가 발생할 여지가 있는 구문");
//			return; // return을 사용 해도 finally 는 출력
		} catch (Exception ex) {
			// TODO: handle exception 사후 처리 및 에러 메시지 띄워야!
			System.out.println("예외 발생" + ex.getMessage()); // ex.toString() 도 사용하기도 함

			ex.printStackTrace();
		} finally {
			System.out.println("무조건 실행 구문"); // 무조건 실행 하는 것은 왜 쓰는 것인가 !!!!!!!!!!!!
		} // connection 닫는 부분!
			//
		System.out.println("프로그램 정상 종료");
	}

}



~~~

<hr style="height: 1px; background: skyblue; "/>

#### TryCatch2

~~~


package g_exception;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;

public class Ex02_TryCatch2 {

	public static void main(String[] args) {
		FileInputStream fis = null;
		try {
//			FileInputStream fis = new FileInputStream("abc.txt");
			fis = new FileInputStream("abc.txt");

			System.out.println("파일 연결");

			fis.read();

		} catch (FileNotFoundException e) {
//			e.printStackTrace();
			System.out.println("파일 없는 예외:" + e.getMessage());
		} catch (IOException e) {
			System.out.println("입출력 예외:" + e.getMessage());
		} catch (Exception e) {
			System.out.println("그외 예외처리");
		} // 외국 저자들은 catch 여러번 쓰기도 함!
		finally {
			try {fis.close();} catch (Exception e) {} //예외의 종류가 많음
		}
	}

}



~~~

<hr style="height: 1px; background: skyblue; "/>

#### throws

~~~


package g_exception;

import java.io.FileInputStream;

public class Ex03_throws {

	public static void main(String[] args) {
		try {
			readFile();
			System.out.println("파일처리");
		} catch (Exception e) {
			System.out.println("예외발생");
		}
	}

	static void readFile() throws Exception { // 모든 발생한 예외를 넘기겠다
		FileInputStream fis = new FileInputStream("xxx.txt");
		System.out.println("파일 연결");
	}

}



~~~

<hr style="height: 1px; background: skyblue; "/>

#### throw

~~~


package g_exception;

public class Ex04_throw {

	public static void main(String[] args) {

		try {
			readArray();
		} catch (Exception ex) {
			System.out.println("예외 발생:" + ex.getMessage()); // getMessage
		}
		System.out.println("정상 종료");
	}

	static void readArray() throws Exception { // throws
		String str[] = { "우리는 한배", "공부즐기시기", "스터디" };

		try {
			for (int i = 0; i <= str.length; i++) {
				System.out.println(str[i]);

			}
		} catch (Exception e) {
			throw new MyException(); // 일부러 예외 발생 시킴
		}
	}

}

~~~

<hr style="height: 1px; background: skyblue; "/>

####

~~~

package g_exception;

public class MyException extends Exception {

	public String getMessage() {
		return "우리가 자주 실수하는 예외";
	}

}

~~~

<hr style="height: 1px; background: skyblue; "/>
